/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.
===============================================================================
*/

-- Find total customers by countries
SELECT
	country,
	COUNT(customer_id) AS customers_amount
FROM
	gold.dim_customers
GROUP BY
	country
ORDER BY
	customers_amount DESC;

-- Find total customers by gender
SELECT
	gender,
	COUNT(customer_id) AS customers_amount
FROM
	gold.dim_customers
GROUP BY
	gender
ORDER BY
	customers_amount DESC;

-- Find total products by category
SELECT
	category,
	COUNT(product_id) AS products_amount
FROM
	gold.dim_products
GROUP BY
	category
ORDER BY
	products_amount DESC;

-- Find the aversage cost in each category
SELECT
	category,
	AVG(product_cost) AS avg_cost
FROM gold.dim_products
GROUP BY
	category
ORDER BY
	avg_cost DESC;

-- Find the total revenue generated by each category
SELECT
	p.category,
	SUM(f.sales_amount) AS total_revenue
FROM
	gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
	ON p.product_key = f.product_key
GROUP BY
	category
ORDER BY
	total_revenue DESC;

-- Find total revenue is generated by each customer
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM
	gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
	ON c.customer_key = f.customer_key
GROUP BY
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY
	total_revenue DESC;

-- Find the distribution of sold items across countries
SELECT
	c.country,
	SUM(f.quantity) AS total_sold_items
FROM
	gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
	ON c.customer_key = f.customer_key
GROUP BY
	c.country
ORDER BY
	total_sold_items DESC;
